---
- name: "install weave"
  command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v1.9.8/weave-daemonset-k8s-1.6.yaml

# Ready count could not be done with jsonpath and filter because of issue
# https://github.com/kubernetes/kubernetes/issues/45546
- name: "get desired weave pod count"
  shell: >
    kubectl get ds --all-namespaces
    | grep weave-net
    | awk '{print $3;}'
  register: get_desired_count_weave

- name: wait for weave DaemonSet to be Ready
  shell: >
    kubectl get ds --all-namespaces
    | grep weave-net
    | awk '{print $5;}'
  register: get_ready_count_weave
  until: (get_desired_count_weave.stdout | int) == (get_ready_count_weave.stdout | int)
  # Wait for 10 minutes
  retries: 200
  delay: 3
