---
- name: create traefik etc directory
  become: yes
  file:
    path: /etc/traefik
    state: directory
    mode: 0755

- name: copy traefik config file
  become: yes
  copy:
    src: traefik.toml
    dest: "/etc/traefik"

- name: create configmap from traefik config file
  command: >
    kubectl create configmap
    traefik-conf
    --namespace=kube-system
    --from-file=/etc/traefik/traefik.toml

- name: copy traefik DaemonSet configuration
  become: yes
  copy:
    src: traefik-daemonset.yml
    dest: "/etc/traefik"

- name: start traefik DaemonSet
  command: >
    kubectl apply -f
    /etc/traefik/traefik-daemonset.yml
    
