# Testing Helm by checking if tiller-deploy pod is ready
- name: "get tiller-deploy ready status"
  command: >
    kubectl get pods -l name=tiller --namespace=kube-system
    -o jsonpath='{.items[*].status.containerStatuses[*].ready}'
  register: get_ready_status

- name: "test tiller-deploy ready status"
  fail:
    msg: "unexpected tiller-deploy ready status: {{get_ready_status.stdout}}"
  when: get_ready_status.stdout != "true"
