- name: render shared-volume bricks locations
  set_fact:
    gluster_bricks: >
      {{gluster_bricks | default('')}}
      {{item}}:/var/bricks/svb1
      {{item}}:/var/bricks/svb2
      {{item}}:/var/bricks/svb3
  with_items: "{{enpoint_list}}"
  tags:
    - gluster_side

- name: create shared-volume (gluster side)
  command: >
    kubectl exec --namespace gluster {{get_name.stdout}}
    gluster volume create shared-volume
    replica 3 {{gluster_bricks | replace('\n', '')}}
    force
  tags:
    - gluster_side

- name: start shared-volume (gluster side)
  command: >
    kubectl exec --namespace gluster {{get_name.stdout}}
    gluster volume start shared-volume
  tags:
    - gluster_side

- name: get shared-volume cumulative size
  shell: >
    kubectl exec --namespace gluster {{get_name.stdout}}
    gluster volume status shared-volume detail |
    grep 'Disk Space Free' |
    grep -o '[0-9]*\.[0-9]*' |
    awk '{s+=$1} END {print s}'
  register: get_tot_size

- set_fact:
    gluster_vol_size: "{{((get_tot_size.stdout | int) / 9) | int}}G"

- name: render shared-volume configuration
  become: yes
  template:
    src: shared-volume.yml
    dest: "/etc/kubenow/yaml/shared-volume.yaml"

- name: create shared-volume (Kubernetes side)
  command: >
    kubectl apply -f
    /etc/kubenow/yaml/shared-volume.yaml
