- name: "get edge labels"
  command: >
    kubectl get nodes {{ groups['edge'] | join(' ') }}
    -o jsonpath='{@..metadata.labels.role}'
  register: get_edge_roles

- name: "test edge labels"
  fail:
    msg: "unexpected edge lables: {{get_edge_roles.stdout}}"
  when: not (get_edge_roles.stdout | match('^(edge\s)*edge$'))
