# requires apache-libcloud
- hosts: localhost
  gather_facts: False
  vars:
    timeout: 1800
    credentials_file_path: "{{playbook_dir}}/../service-account.json"
    img_version: "v020"
  tasks:
  - name: "read credentials file"
    set_fact:
      credentials_file: "{{ lookup('file', credentials_file_path) }}"
  - name: "set image facts"
    set_fact:
      img_name: "kubenow-{{img_version}}"
      img_source: "https://storage.googleapis.com/kubenow-images/kubenow-{{img_version}}.tar.gz"
  - name: "import GCE image (if not present)"
    gce_img:
      name: "{{img_name}}"
      source: "{{img_source}}"
      timeout: "{{timeout}}"
    environment:
      GCE_EMAIL: "{{credentials_file | json_query('[client_email][0]')}}"
      GCE_PROJECT: "{{credentials_file | json_query('[project_id][0]')}}"
      GCE_CREDENTIALS_FILE_PATH: "{{credentials_file_path}}"
    async: "{{timeout}}"
    poll: 0
    register: kubenow_upload
  - name: "wait for image upload to be done"
    async_status: jid={{ kubenow_upload.ansible_job_id }}
    register: upload_status
    until: upload_status.finished
    retries: "{{((timeout | int) / 5) | int}}"
    delay: 5
