- hosts: master
  gather_facts: False
  roles:
    - { role: heketi-gluster-server, tags: [ 'heketi-glusterfs' ] }
    - { role: heketi, tags: [ 'heketi-glusterfs' ] }
    - { role: heketi-storage, tags: [ 'heketi-glusterfs' ] }
    - { role: heketi-pvc, tags: [ 'heketi-glusterfs' ] }

