- hosts: master
  gather_facts: False
  roles:
    - { role: common, tags: [ 'minimal' ] }
    - { role: weave-network, tags: [ 'minimal' ] }
    - { role: start-helm, tags: [ 'minimal' ] }
    - { role: gluster-server, tags: [ 'glusterfs' ] }
    - { role: shared-volume, tags: [ 'glusterfs' ] }
    - { role: traefik, tags: [ 'traefik' ] }

- hosts: edge
  gather_facts: False
  roles:
    - { role: cloudflare, tags: [ 'cloudflare' ] }
