---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-volume-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ vol_size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ host_path }}"
